@extends('manager.layout.master')
@section('title', 'Patients')
@section('page-content')
<div class="rounded-xl border border-gray-200 bg-white shadow-sm">
    <div class="flex items-center justify-between border-b border-gray-100 px-5 py-4"><div><h1 class="font-display text-base font-bold text-hut-dark">Patients</h1><p class="text-xs text-gray-500">Manage the clinic's separate patient records.</p></div><a href="{{ route('manager.patients.create') }}" class="btn rounded-lg bg-hut-yellow px-3.5 py-2 text-xs font-semibold text-hut-dark">Add Patient</a></div>
    @if(session('success'))<div class="mx-5 mt-4 rounded-lg bg-green-50 px-4 py-3 text-sm text-green-700">{{ session('success') }}</div>@endif
    <div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="border-b border-gray-100 bg-gray-50 text-xs uppercase text-gray-500"><tr><th class="px-5 py-3">Patient</th><th class="px-3 py-3">Phone</th><th class="px-3 py-3">Patient ID</th><th class="px-5 py-3 text-right">Actions</th></tr></thead><tbody class="divide-y divide-gray-100">
        @forelse($patients as $patient)<tr><td class="px-5 py-3"><div class="font-semibold text-hut-dark">{{ $patient->name }}</div><div class="text-xs text-gray-500">{{ $patient->cnic ?: 'No CNIC' }}</div></td><td class="px-3 py-3 text-gray-600">{{ $patient->phone ?: '-' }}</td><td class="px-3 py-3 text-gray-600">{{ $patient->patient_number }}</td><td class="px-5 py-3 text-right"><a href="{{ route('manager.patients.history', $patient) }}" class="mr-3 inline-flex h-8 w-8 items-center justify-center rounded-lg text-slate-600 hover:bg-slate-50" aria-label="View patient history" title="View patient history"><x-icons.eye class="h-4 w-4" /></a><a href="{{ route('manager.patients.edit', $patient) }}" class="inline-flex h-8 w-8 items-center justify-center rounded-lg text-hut-green hover:bg-hut-green/10" aria-label="Edit patient" title="Edit patient"><x-icons.edit class="h-4 w-4" /></a><form class="ml-3 inline" method="POST" action="{{ route('manager.patients.destroy', $patient) }}" onsubmit="return confirm('Delete this patient?')">@csrf @method('DELETE')<button type="submit" class="inline-flex h-8 w-8 items-center justify-center rounded-lg text-red-600 hover:bg-red-50" aria-label="Delete patient" title="Delete patient"><x-icons.trash class="h-4 w-4" /></button></form></td></tr>@empty<tr><td colspan="4" class="px-5 py-10 text-center text-sm text-gray-500">No patients found.</td></tr>@endforelse
    </tbody></table></div><div class="px-5 py-4">{{ $patients->links() }}</div>
</div>
@endsection
