@extends('layouts.admin')
@section('title', 'Report Details')

@section('content')
@php
    $data = is_array($report->data_snapshot) ? $report->data_snapshot : [];
    $money = fn ($n) => 'Rs. ' . number_format((float) $n, 0);
@endphp
<div class="space-y-6">
    <div class="flex flex-wrap items-start justify-between gap-3">
        <div>
            <a href="{{ route('manager.reports.index') }}" class="text-sm text-gray-500 hover:text-hut-dark">← Back to reports</a>
            <h2 class="mt-1 text-2xl font-semibold text-hut-dark">{{ $report->name }}</h2>
            <p class="text-sm text-gray-500">
                Generated {{ $report->generated_at?->format('M d, Y H:i') ?? $report->created_at?->format('M d, Y H:i') }}
            </p>
        </div>
        <div class="flex flex-wrap gap-2">
            <a href="{{ route('manager.reports.export.pdf', $report) }}" target="_blank"
               class="rounded-lg bg-hut-dark px-4 py-2 text-sm font-semibold text-white hover:bg-gray-800">Export PDF</a>
            <a href="{{ route('manager.reports.export.excel', $report) }}"
               class="rounded-lg bg-hut-yellow px-4 py-2 text-sm font-semibold text-hut-dark hover:bg-amber-400">Export Excel</a>
        </div>
    </div>

    <div class="grid gap-4 md:grid-cols-3">
        <div class="rounded-2xl border border-gray-200 bg-white p-4 shadow-sm">
            <p class="text-xs font-semibold uppercase tracking-wide text-gray-400">Report type</p>
            <p class="mt-1 font-semibold text-hut-dark">{{ ucfirst($report->type) }}</p>
        </div>
        <div class="rounded-2xl border border-gray-200 bg-white p-4 shadow-sm">
            <p class="text-xs font-semibold uppercase tracking-wide text-gray-400">Generated by</p>
            <p class="mt-1 font-semibold text-hut-dark">{{ $report->user?->name ?? '—' }}</p>
        </div>
        <div class="rounded-2xl border border-gray-200 bg-white p-4 shadow-sm">
            <p class="text-xs font-semibold uppercase tracking-wide text-gray-400">Date range</p>
            <p class="mt-1 font-semibold text-hut-dark">
                {{ $report->filters['date_from'] ?? '—' }} — {{ $report->filters['date_to'] ?? '—' }}
            </p>
        </div>
    </div>

    @if(($report->type ?? '') === 'sales')
        <div class="grid gap-4 sm:grid-cols-3">
            <div class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
                <p class="text-xs font-semibold uppercase text-gray-400">Total sales</p>
                <p class="mt-2 text-2xl font-bold text-hut-dark">{{ $money($data['total_sales'] ?? 0) }}</p>
            </div>
            <div class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
                <p class="text-xs font-semibold uppercase text-gray-400">Orders</p>
                <p class="mt-2 text-2xl font-bold text-hut-dark">{{ number_format((float) ($data['order_count'] ?? 0)) }}</p>
            </div>
            <div class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
                <p class="text-xs font-semibold uppercase text-gray-400">Items qty</p>
                <p class="mt-2 text-2xl font-bold text-hut-dark">{{ number_format((float) ($data['total_quantity'] ?? 0)) }}</p>
            </div>
        </div>

        <div class="rounded-2xl border border-gray-200 bg-white shadow-sm overflow-hidden">
            <div class="border-b border-gray-100 px-4 py-3">
                <h3 class="font-semibold text-hut-dark">Items sold</h3>
            </div>
            <div class="overflow-x-auto">
                <table class="min-w-full text-sm">
                    <thead class="bg-gray-50 text-left text-xs uppercase text-gray-500">
                        <tr>
                            <th class="px-4 py-3">Item</th>
                            <th class="px-4 py-3 text-right">Qty</th>
                            <th class="px-4 py-3 text-right">Revenue</th>
                        </tr>
                    </thead>
                    <tbody class="divide-y divide-gray-100">
                        @forelse(($data['items_sold'] ?? []) as $key => $row)
                            @php
                                $name = is_array($row) ? ($row['name'] ?? $key) : $key;
                                $qty = is_array($row) ? ($row['quantity'] ?? 0) : 0;
                                $rev = is_array($row) ? ($row['revenue'] ?? 0) : 0;
                            @endphp
                            <tr>
                                <td class="px-4 py-3 font-medium text-hut-dark">{{ $name }}</td>
                                <td class="px-4 py-3 text-right text-gray-600">{{ number_format((float) $qty) }}</td>
                                <td class="px-4 py-3 text-right text-gray-700">{{ $money($rev) }}</td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="3" class="px-4 py-8 text-center text-gray-400">
                                    No sales in this period. Complete POS or online orders, then generate the report again.
                                </td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
    @elseif(($report->type ?? '') === 'financial')
        <div class="grid gap-4 sm:grid-cols-3">
            <div class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
                <p class="text-xs font-semibold uppercase text-gray-400">Revenue</p>
                <p class="mt-2 text-2xl font-bold text-hut-dark">{{ $money($data['revenue'] ?? 0) }}</p>
            </div>
            <div class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
                <p class="text-xs font-semibold uppercase text-gray-400">Expenses</p>
                <p class="mt-2 text-2xl font-bold text-hut-dark">{{ $money($data['total_expenses'] ?? 0) }}</p>
            </div>
            <div class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm">
                <p class="text-xs font-semibold uppercase text-gray-400">Net profit</p>
                <p class="mt-2 text-2xl font-bold text-hut-dark">{{ $money($data['net_profit'] ?? 0) }}</p>
            </div>
        </div>
    @elseif(($report->type ?? '') === 'inventory')
        <div class="grid gap-4 sm:grid-cols-4">
            <div class="rounded-2xl border border-gray-200 bg-white p-4 shadow-sm">
                <p class="text-xs text-gray-400 uppercase">Variants</p>
                <p class="text-xl font-bold">{{ $data['total_variants'] ?? 0 }}</p>
            </div>
            <div class="rounded-2xl border border-gray-200 bg-white p-4 shadow-sm">
                <p class="text-xs text-gray-400 uppercase">Stock value</p>
                <p class="text-xl font-bold">{{ $money($data['total_stock_value'] ?? 0) }}</p>
            </div>
            <div class="rounded-2xl border border-gray-200 bg-white p-4 shadow-sm">
                <p class="text-xs text-gray-400 uppercase">Low stock</p>
                <p class="text-xl font-bold text-amber-600">{{ $data['low_stock_count'] ?? 0 }}</p>
            </div>
            <div class="rounded-2xl border border-gray-200 bg-white p-4 shadow-sm">
                <p class="text-xs text-gray-400 uppercase">Out of stock</p>
                <p class="text-xl font-bold text-red-600">{{ $data['out_of_stock_count'] ?? 0 }}</p>
            </div>
        </div>
    @else
        <div class="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm">
            <h3 class="font-semibold text-hut-dark mb-4">Summary</h3>
            <dl class="grid gap-3 sm:grid-cols-2">
                @foreach($data as $key => $value)
                    @if(!is_array($value))
                        <div class="rounded-xl bg-gray-50 px-4 py-3">
                            <dt class="text-xs uppercase text-gray-400">{{ str_replace('_', ' ', $key) }}</dt>
                            <dd class="mt-1 font-semibold text-hut-dark">{{ is_numeric($value) ? number_format((float)$value, 2) : $value }}</dd>
                        </div>
                    @endif
                @endforeach
            </dl>
        </div>
    @endif
</div>
@endsection
