@extends('layouts.admin')

@section('title', 'Report Details')

@section('content')
<div class="space-y-6">
    <div class="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
        <div>
            <h2 class="text-xl font-semibold text-hut-dark">{{ $report->name }}</h2>
            <p class="text-sm text-gray-500">{{ ucfirst($report->type) }} report generated on {{ $report->generated_at->format('M d, Y H:i') }}.</p>
        </div>
        <div class="flex flex-wrap gap-2">
            <a href="{{ route('manager.reports.index') }}" class="rounded-lg border border-gray-300 bg-white px-4 py-2 text-sm text-gray-700 hover:bg-gray-50">Back to reports</a>
            <a href="{{ route('manager.reports.export.pdf', $report) }}" class="rounded-lg bg-hut-dark px-4 py-2 text-sm font-semibold text-white hover:bg-gray-800">Export PDF</a>
            <a href="{{ route('manager.reports.export.excel', $report) }}" class="rounded-lg bg-hut-yellow px-4 py-2 text-sm font-semibold text-hut-dark hover:bg-amber-500">Export Excel</a>
        </div>
    </div>

    <div class="grid gap-4 md:grid-cols-3">
        <div class="rounded-2xl border border-gray-200 bg-white p-4 shadow-sm">
            <h3 class="text-sm font-semibold text-gray-600 uppercase tracking-wide">Report Type</h3>
            <p class="mt-2 text-sm text-gray-900">{{ ucfirst($report->type) }}</p>
        </div>
        <div class="rounded-2xl border border-gray-200 bg-white p-4 shadow-sm">
            <h3 class="text-sm font-semibold text-gray-600 uppercase tracking-wide">Generated by</h3>
            <p class="mt-2 text-sm text-gray-900">{{ $report->user?->name ?? 'Unknown' }}</p>
        </div>
        <div class="rounded-2xl border border-gray-200 bg-white p-4 shadow-sm">
            <h3 class="text-sm font-semibold text-gray-600 uppercase tracking-wide">Date range</h3>
            <p class="mt-2 text-sm text-gray-900">{{ $report->filters['date_from'] ?? 'N/A' }} — {{ $report->filters['date_to'] ?? 'N/A' }}</p>
        </div>
    </div>

    <div class="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm">
        <h3 class="text-lg font-semibold text-hut-dark">Report data snapshot</h3>
        <pre class="mt-4 overflow-x-auto rounded-lg bg-gray-950/95 p-4 text-xs text-white">{{ json_encode($report->data_snapshot, JSON_PRETTY_PRINT) }}</pre>
    </div>
</div>
@endsection
