@extends('manager.layout.master')
@section('title', 'Vital Signs')
@section('page-content')
<div class="space-y-6"><div><h1 class="font-display text-lg font-bold text-hut-dark">Vital Signs</h1><p class="text-sm text-gray-500">Record observations for active inpatients.</p></div>
@if(session('success'))<div class="rounded-lg bg-green-50 px-4 py-3 text-sm text-green-700">{{ session('success') }}</div>@endif
<form method="POST" action="{{ route('manager.vitals.store') }}" class="grid gap-3 rounded-xl border border-gray-200 bg-white p-5 md:grid-cols-4">@csrf
<select name="hospital_admission_id" required class="rounded-lg border-gray-200"><option value="">Admission</option>@foreach($admissions as $admission)<option value="{{ $admission->id }}">{{ $admission->admission_number }} — {{ $admission->patient?->name }}</option>@endforeach</select>
<input type="datetime-local" name="recorded_at" value="{{ now()->format('Y-m-d\TH:i') }}" required class="rounded-lg border-gray-200"><input name="temperature" type="number" step="0.1" placeholder="Temp °C" class="rounded-lg border-gray-200"><input name="blood_pressure" placeholder="BP e.g. 120/80" class="rounded-lg border-gray-200"><input name="pulse" type="number" placeholder="Pulse bpm" class="rounded-lg border-gray-200"><input name="respiratory_rate" type="number" placeholder="Respiratory/min" class="rounded-lg border-gray-200"><input name="oxygen_saturation" type="number" step="0.1" placeholder="Oxygen %" class="rounded-lg border-gray-200"><input name="weight" type="number" step="0.01" placeholder="Weight kg" class="rounded-lg border-gray-200"><input name="pain_score" type="number" min="0" max="10" placeholder="Pain 0-10" class="rounded-lg border-gray-200"><textarea name="notes" placeholder="Notes" class="md:col-span-3 rounded-lg border-gray-200"></textarea><button class="rounded-lg bg-hut-dark px-4 py-2 text-sm font-semibold text-white">Record Vitals</button></form>
<div class="overflow-x-auto rounded-xl border border-gray-200 bg-white"><table class="w-full text-left text-sm"><thead class="border-b bg-gray-50 text-xs uppercase text-gray-500"><tr><th class="px-5 py-3">Admission</th><th class="px-3 py-3">Patient</th><th class="px-3 py-3">Temperature</th><th class="px-3 py-3">BP</th><th class="px-3 py-3">Pulse</th><th class="px-3 py-3">O₂</th><th class="px-5 py-3">Recorded by</th></tr></thead><tbody class="divide-y">@forelse($vitals as $vital)<tr><td class="px-5 py-3">{{ $vital->admission?->admission_number }}</td><td class="px-3 py-3">{{ $vital->admission?->patient?->name }}</td><td class="px-3 py-3">{{ $vital->temperature ?? '—' }}</td><td class="px-3 py-3">{{ $vital->blood_pressure ?? '—' }}</td><td class="px-3 py-3">{{ $vital->pulse ?? '—' }}</td><td class="px-3 py-3">{{ $vital->oxygen_saturation ?? '—' }}</td><td class="px-5 py-3">{{ $vital->recorder?->name }}</td></tr>@empty<tr><td colspan="7" class="px-5 py-10 text-center text-gray-500">No vital signs recorded.</td></tr>@endforelse</tbody></table><div class="px-5 py-4">{{ $vitals->links() }}</div></div></div>
@endsection
